### ISSUE TITLE
Checkpoints Download

### ISSUE THREAD

**Issue by adamcread** [azadis/CompositionalGAN#11]
I attempted to download the pre-trained models using the script however the link doesn't seem to be working, please could I get a new one?

**Comment by buzhengbujiban** [comment]
I also encountered the same problem. Is there a new way to get checkpoints

**Comment by zmw1003** [comment]
Can you share the dataset? The download link has expired

**Comment by azadis** [comment]
data and checkpoints can be found here: https://drive.google.com/drive/folders/1Ge9NrLnWnt2wIjLBoClEY_tIPd17LXGF?usp=sharing
