### ISSUE TITLE
The data set download link has expired. Can you provide a new download address? Thank you

### ISSUE THREAD

**Issue by zmw1003** [azadis/CompositionalGAN#12]

**Comment by hqg19971124** [comment]
Do you have the dataset of compositionGAN you obtained?

**Comment by azadis** [comment]
Datasets can be found here: https://drive.google.com/drive/folders/1Ge9NrLnWnt2wIjLBoClEY_tIPd17LXGF?usp=sharing

**Comment by hqg19971124** [comment]
Thank you very much!!






发件人：Samaneh Azadi ***@***.***>
发送日期：2022-09-24 16:58:30
收件人：azadis/CompositionalGAN ***@***.***>
抄送人：hqg19971124 ***@***.***>,Comment ***@***.***>
主题：Re: [azadis/CompositionalGAN] The data set download link has expired. Can you provide a new download address? Thank you (Issue #12)

Datasets can be found here: https://drive.google.com/drive/folders/1Ge9NrLnWnt2wIjLBoClEY_tIPd17LXGF?usp=sharing
